[package]
name = "serial-to-metrics"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.23", features = ["derive", "env"] }
serialport = { version = "4.7.0", features  = [], default-features = false }
ureq = "2.12.1"
